const modules=[
{icon:'💻',title:'Meet the Computer',desc:'What a computer is, what it can do and where we see computers.',points:['A computer is an electronic machine.','It can help us learn, draw, type, listen and watch.','Computers are used at home, school, hospitals, banks and shops.'],challenge:'Say two useful things a computer can help you do.',badge:'💻 Computer Explorer'},
{icon:'🖥️',title:'Know Your Computer',desc:'Monitor, keyboard, mouse, printer, speakers, webcam and system unit.',points:['Monitor shows pictures, words and videos.','Keyboard helps us type letters and numbers.','Mouse helps us point, click, drag and scroll.','Printer puts digital work on paper.'],challenge:'Point to the monitor, keyboard and mouse on a real computer.',badge:'🖥️ Parts Detective'},
{icon:'🖱️',title:'Mouse Master',desc:'Move, point, left-click, double-click, drag-and-drop and scroll.',points:['Move the mouse gently.','One click selects an item.','Double-click can open an item.','Drag means hold, move and release.'],challenge:'Use the Practice Lab to identify all four computer parts.',badge:'🖱️ Mouse Master'},
{icon:'⌨️',title:'Keyboard Explorer',desc:'Letters, numbers, Spacebar, Enter, Backspace and arrow keys.',points:['A–Z keys type letters.','0–9 keys type numbers.','Spacebar makes a space.','Backspace removes the character before the cursor.','Enter can start a new line or confirm an action.'],challenge:'Type your first name slowly and correctly.',badge:'⌨️ Keyboard Hero'},
{icon:'🪟',title:'Screen & Windows',desc:'Desktop, icons, open, close, minimize and maximize.',points:['The desktop is the main work area.','An icon represents an app, file or folder.','The X button closes a window.','Minimize hides a window without closing it.'],challenge:'Ask an adult to show you one desktop icon and one open window.',badge:'🪟 Desktop Explorer'},
{icon:'🎨',title:'Digital Artist',desc:'Pencil, brush, colours, shapes and eraser.',points:['Digital drawing uses tools on a screen.','Choose a colour before drawing.','Shapes help create circles, squares and triangles.','Eraser removes part of a drawing.'],challenge:'Draw a house with a sun, door and two windows.',badge:'🎨 Digital Artist'},
{icon:'✍️',title:'First Typing Adventure',desc:'Type simple letters, words and short sentences accurately.',points:['Accuracy comes before speed.','Look at the word, then type carefully.','Use Spacebar between words.','Use Backspace to fix a mistake.'],challenge:'Type: I LOVE COMPUTERS',badge:'✍️ Typing Star'},
{icon:'🛡️',title:'Internet & Safety',desc:'Internet basics, private information, passwords and asking an adult.',points:['The internet connects many devices and services.','Never share passwords.','Do not share your home address with strangers online.','Ask a parent or teacher before opening unknown links.','Tell a trusted adult if something online feels uncomfortable.'],challenge:'Answer: Should you share your password with an online stranger? No!',badge:'🛡️ Safety Hero'},
{icon:'🤖',title:'Meet AI',desc:'What AI is, smart tasks, examples and the difference between AI and ordinary tools.',points:['AI means Artificial Intelligence.','Some AI systems can recognize speech, pictures or patterns.','Not every electronic device is AI.','AI can make mistakes, so important answers should be checked.'],challenge:'Name one place where you may have seen an AI feature.',badge:'🤖 AI Explorer'},
{icon:'✨',title:'My First AI Prompt',desc:'Build simple instructions using a character, place and action.',points:['A prompt is an instruction or request given to an AI system.','Clear details can help produce a more useful result.','Never put private information into a prompt.','Ask an adult when using online AI tools.'],challenge:'Make this prompt better: “Robot.” Try: “A friendly robot reading a book on the Moon.”',badge:'✨ Prompt Creator'}
];
let state=JSON.parse(localStorage.getItem('brightbyte-class1')||'{"done":[],"stars":120}');
const targetList=['Monitor','Keyboard','Mouse','Printer'];let targetIndex=0;
function save(){localStorage.setItem('brightbyte-class1',JSON.stringify(state));render()}
function go(id){document.getElementById(id).scrollIntoView({behavior:'smooth'});document.getElementById('nav').classList.remove('open')}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.remove('show'),1900)}
function render(){const wrap=document.getElementById('modules');wrap.innerHTML='';modules.forEach((m,i)=>{const done=state.done.includes(i);const el=document.createElement('article');el.className='module '+(done?'done':'');el.innerHTML=`<div class="ico">${m.icon}</div><div class="copy"><small>MODULE ${i+1}</small><h3>${m.title}</h3><p>${m.desc}</p></div><span class="state">${done?'✓ DONE':'OPEN →'}</span>`;el.onclick=()=>openLesson(i);wrap.appendChild(el)});document.getElementById('stars').textContent=state.stars;document.getElementById('gameStars').textContent=state.stars;document.getElementById('parentStars').textContent=state.stars;const n=state.done.length,p=n*10;document.getElementById('doneCount').textContent=n;document.getElementById('lessonsDone').textContent=n;document.getElementById('badgeCount').textContent=n;document.getElementById('parentBadges').textContent=`${n} / 10`;document.getElementById('percent').textContent=p+'%';document.getElementById('heroBar').style.width=p+'%';document.getElementById('parentBar').style.width=p+'%';const next=modules[state.done.findIndex? modules.findIndex((_,i)=>!state.done.includes(i)):-1]||modules[9];document.getElementById('missionTitle').textContent=next.title;document.getElementById('focus').textContent=next.title;document.getElementById('teacherNote').textContent=n===10?'Excellent! All Class 1 demo modules are complete. Review weak areas and try the final certificate.':`Next recommended focus: ${next.title}. Keep the session short and practical.`;const bg=document.getElementById('badgeGrid');bg.innerHTML='';modules.forEach((m,i)=>{bg.innerHTML+=`<div class="badge ${state.done.includes(i)?'':'locked'}"><b>${m.badge.split(' ')[0]}</b><span>${m.badge.substring(m.badge.indexOf(' ')+1)}</span></div>`})}
function openLesson(i){const m=modules[i];document.getElementById('modalBody').innerHTML=`<div class="lessonHero"><div class="bigico">${m.icon}</div><small>MODULE ${i+1} • MINI LESSON</small><h2>${m.title}</h2><p>${m.desc}</p></div><div class="learnbox"><h4>📚 What we learn</h4><ul>${m.points.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="challenge"><b>🎯 Practical Challenge</b><p>${m.challenge}</p></div><button class="complete" onclick="completeModule(${i})">${state.done.includes(i)?'✓ Completed — Review Again':'Complete Lesson • +20 ⭐'}</button>`;document.getElementById('modal').classList.add('open')}
function completeModule(i){if(!state.done.includes(i)){state.done.push(i);state.stars+=20;save();toast('Great work! +20 Stars ⭐')}else toast('Lesson already completed ✓');closeModal()}
function closeModal(){document.getElementById('modal').classList.remove('open')}
function openQuiz(){document.getElementById('modalBody').innerHTML=`<div class="lessonHero"><div class="bigico">🧠</div><h2>Quick Quiz</h2><p>Which device helps us type letters and numbers?</p></div><div class="quizBtns"><button onclick="answer(false)">🖱️ Mouse</button><button onclick="answer(true)">⌨️ Keyboard</button><button onclick="answer(false)">🖨️ Printer</button></div>`;document.getElementById('modal').classList.add('open')}
function answer(ok){if(ok){state.stars+=10;save();closeModal();toast('Correct! +10 Stars ⭐')}else toast('Good try — think about typing!')}
function showCertificate(){document.getElementById('modalBody').innerHTML=`<div class="lessonHero"><div class="bigico">🏅</div><small>CERTIFICATE OF ACHIEVEMENT</small><h2>Computer & AI Explorer</h2><p>This demo certificate recognizes completion of the BrightByte Kids Lab Class 1 learning journey.</p><div class="learnbox"><h4>Ayaan • Class 1</h4><p>Progress: ${state.done.length}/10 modules • Stars: ${state.stars}</p></div></div>`;document.getElementById('modal').classList.add('open')}
function resetProgress(){if(confirm('Reset demo progress and stars?')){state={done:[],stars:120};save();toast('Demo reset') }}
document.getElementById('menu').onclick=()=>document.getElementById('nav').classList.toggle('open');document.querySelectorAll('.parts button').forEach(b=>b.onclick=()=>{if(b.dataset.part===targetList[targetIndex]){state.stars+=5;save();toast('Excellent! +5 Stars ⭐');targetIndex=(targetIndex+1)%targetList.length;document.getElementById('target').textContent=targetList[targetIndex]}else toast('Try another part 🙂')});document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};render();
